"""
Lógica de negocio de mcp-orchestrator.

Análisis y generación de DAGs (Directed Acyclic Graphs).
"""

from __future__ import annotations

import ast
from pathlib import Path
from typing import Any

from mcp_shared.errors import FileNotFoundError, ParseError, ValidationError


def parse_airflow_dag(file_path: Path) -> dict[str, Any]:
    """Parsea un archivo Python de Airflow usando AST para extraer tareas y dependencias."""
    if not file_path.exists() or not file_path.is_file():
        raise FileNotFoundError(str(file_path))

    try:
        content = file_path.read_text(encoding="utf-8")
        tree = ast.parse(content, filename=str(file_path))
    except Exception as exc:
        raise ParseError(source=str(file_path), reason=str(exc)) from exc

    tasks = []
    dependencies = []
    dag_id = "unknown"

    for node in ast.walk(tree):
        # Encontrar DAG ID y tareas instanciadas
        if isinstance(node, ast.Assign):
            # 1. DAG ID
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id.lower() == "dag":
                    if isinstance(node.value, ast.Call) and node.value.args:
                        if isinstance(node.value.args[0], ast.Constant):
                            dag_id = str(node.value.args[0].value)

            # 2. Tareas (operadores instanciados)
            if isinstance(node.value, ast.Call) and isinstance(node.value.func, ast.Name):
                if "Operator" in node.value.func.id or "Sensor" in node.value.func.id:
                    for target in node.targets:
                        if isinstance(target, ast.Name):
                            tasks.append(
                                {
                                    "var_name": target.id,
                                    "operator": node.value.func.id,
                                }
                            )

        # Encontrar dependencias (operador >> o <<)
        elif isinstance(node, ast.Expr) and isinstance(node.value, ast.BinOp):
            if isinstance(node.value.op, (ast.RShift, ast.LShift)):
                left = getattr(node.value.left, "id", str(node.value.left.__class__.__name__))
                right = getattr(node.value.right, "id", str(node.value.right.__class__.__name__))
                if isinstance(node.value.op, ast.RShift):
                    dependencies.append(f"{left} -> {right}")
                else:
                    dependencies.append(f"{right} -> {left}")

    return {
        "file": file_path.name,
        "dag_id": dag_id,
        "tasks_found": len(tasks),
        "tasks": tasks,
        "dependencies": dependencies,
    }


def validate_dag_acyclicity(edges: list[tuple[str, str]]) -> dict[str, Any]:
    """Verifica si un grafo definido por sus aristas contiene ciclos."""
    graph: dict[str, list[str]] = {}
    for u, v in edges:
        graph.setdefault(u, []).append(v)
        graph.setdefault(v, [])

    visited = set()
    rec_stack = set()

    def dfs(node: str) -> bool:
        visited.add(node)
        rec_stack.add(node)

        for neighbor in graph.get(node, []):
            if neighbor not in visited:
                if dfs(neighbor):
                    return True
            elif neighbor in rec_stack:
                return True

        rec_stack.remove(node)
        return False

    has_cycle = False
    for node in graph:
        if node not in visited:
            if dfs(node):
                has_cycle = True
                break

    return {
        "is_valid": not has_cycle,
        "has_cycle": has_cycle,
        "nodes_analyzed": len(graph),
        "edges_analyzed": len(edges),
    }


def generate_boilerplate_dag(dag_id: str, tasks: list[str]) -> str:
    """Genera un boilerplate en Python para un DAG de Airflow."""
    if not dag_id or not tasks:
        raise ValidationError(
            field="dag_id/tasks", message="Se requiere dag_id y al menos una tarea."
        )

    lines = [
        "from datetime import datetime, timedelta",
        "from airflow import DAG",
        "from airflow.operators.empty import EmptyOperator",
        "",
        "default_args = {",
        "    'owner': 'airflow',",
        "    'depends_on_past': False,",
        "    'retries': 1,",
        "    'retry_delay': timedelta(minutes=5),",
        "}",
        "",
        "with DAG(",
        f"    dag_id='{dag_id}',",
        "    default_args=default_args,",
        "    description='Boilerplate DAG generated by MCP',",
        "    schedule_interval=timedelta(days=1),",
        "    start_date=datetime(2024, 1, 1),",
        "    catchup=False,",
        ") as dag:",
        "",
    ]

    for task in tasks:
        var_name = task.replace("-", "_").replace(" ", "_").lower()
        lines.append(f"    {var_name} = EmptyOperator(task_id='{task}')")

    lines.append("")
    if len(tasks) > 1:
        var_names = [t.replace("-", "_").replace(" ", "_").lower() for t in tasks]
        lines.append(f"    {' >> '.join(var_names)}")

    return "\n".join(lines)
